### ISSUE TITLE
Unable to keybind the use key to E or G keys

### ISSUE THREAD

**Issue by talso** [TheStaticVoid/StaTech-Industry#150]
I've got a weird set of keybinds I don't put 'use item' on mouse 2.

I've confirmed in the interface and options.txt there's no conflicts.

key_key.use:key.keyboard.g

just playing around with the binds it seems like the 'E' has the same issue.

I've moved it to 't' for now, which I'm sure I'll get used to, just odd.

**Comment by TheStaticVoid** [comment]
For G I couldn't get it to work, but for E it works just fine.
