### ISSUE TITLE
Magic questline missing items

### ISSUE THREAD

**Issue by Chtholly-dev** [TheStaticVoid/StaTech-Industry#194]
There are currently 2 quests which have missing items from them.
![StaTech_Industry_07_06_2023_22_18_36](https://github.com/TheStaticVoid/StaTech-Industry/assets/52564247/122db601-4b0a-45f5-bd93-e294e3075d17)
![StaTech_Industry_07_06_2023_22_18_28](https://github.com/TheStaticVoid/StaTech-Industry/assets/52564247/30396199-d8fd-481e-8d91-8574dbbaa385)

**Comment by TheStaticVoid** [comment]
Including in this issue.
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/6089108/e0b377e5-6e6b-4015-a9cd-25be6b8836e8)

From [Discord](https://discord.com/channels/1080389179537637456/1116457774675660951)
