### ISSUE TITLE
Game crashes when you right click a basin with a Rapier

### ISSUE THREAD

**Issue by PapaZ810** [TheStaticVoid/StaTech-Industry#196]
[Crash report here](https://github.com/TheStaticVoid/StaTech-Industry/files/11683904/crash-2023-06-07_21.54.57-client.txt)

Was trying to grab some bronze out of my basin and was holding my Rapier out and the game crashed. Not too pressing just something to know. If I had to guess, it probably happens with other Simply Swords weapons as well.

**Comment by TheStaticVoid** [comment]
This might be related to an earlier bug with right clicking basins causing crashes. Looks to be a Create related bug, will need to investigate.
