### ISSUE TITLE
Can't leave item recipes or quest book

### ISSUE THREAD

**Issue by BVRK24** [TheStaticVoid/StaTech-Industry#235]
After opening the quest book and looking at item recipes when press escape to leave it will alternate between an inventory view and the quest book, this can be left with attempting a crafting recipe you can make, otherwise you are forced to close the game

**Comment by lyze237** [comment]
From the discord servers #faq channel:

> This is a bug with REI or FTB Quests as of right now. I've reached out to the developers to try and get it resolved. For now, avoid clicking the quest book in your inventory when looking at recipes. You can escape the loop by pulling up the FTB Chunks menu (right next to the questbook icon) and then click the icon in the top left again. From there you can press 'ESC' to get back to the game. Track it's progress here: https://github.com/FTBTeam/FTB-Mods-Issues/issues/828

**Comment by BVRK24** [comment]
Oh rightio!, Thanks for telling me
