### ISSUE TITLE
A new item transport mod...

### ISSUE THREAD

**Issue by NotKingsley1** [TheStaticVoid/StaTech-Industry#240]
Lately, some servers have been noticing that some of the item transport mods such as modern dynamics, have lagging them out, we might want to find a mod to transport items and fluids, but be server friendly

**Comment by TheStaticVoid** [comment]
Just because the public server runs on subpar hardware and those mods showed as a high contributor to lag I'm not looking to remove them. MI pipes are extremely optimized, the MD pipes not so much. This won't be an issue for players in singleplayer and/or small friend group sized servers.
