### ISSUE TITLE
Nether Biomes are not generating correctly

### ISSUE THREAD

**Issue by Pixl64** [TheStaticVoid/StaTech-Industry#255]
When creating worlds, I found that the nether biomes were not generating with the BYG and Promenade biomes included in actual generation. However, I found that the locations for them (in f3 and the /locate biome command) were working. 

I feel this may have something to do with Amplified Nether, but I seem to remember using them both before
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/85389249/22848b03-644c-483e-bb36-5b064dfb3c49)
As seen above, the biome shown in f3 is a byg biome, but the game just generated a standard nether wastes biome.

**Comment by Pixl64** [comment]
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/85389249/29449013-68c0-47b7-80cb-747e63207cc4)
This also seems to be a slight issue in the end, with biomes not generating correctly (although I'm not sure what this biome is supposed to look like so I could be wrong)

**Comment by TheStaticVoid** [comment]
I'll have to do some testing with this. I've never seen nether biomes have problem but I have noticed the end doesn't look quite right in the pack.

**Comment by TheStaticVoid** [comment]
Confirmed. BYG has an unlisted dependency on an older version of TerraBlender. https://github.com/AOCAWOL/BYG/issues/1114#issuecomment-1553942204

**Comment by TheStaticVoid** [comment]
Pushing change to 1.1.0 release. Sorry for the inconvenience until then. https://github.com/TheStaticVoid/StaTech-Industry/commit/79cc4cf7b17efed793dbeec0b2d0f7eb0c06a334
