### ISSUE TITLE
Installation of 1.0.5hotfix crashes Prism Launcher due to invalid projectID field

### ISSUE THREAD

**Issue by Danacus** [TheStaticVoid/StaTech-Industry#262]
PrismLauncher gives the following error when trying to install this modpack:

```
Exception: "'project_id's parent does not contain 'project_id'"
terminate called after throwing an instance of 'Json::JsonException'
  what():  'project_id's parent does not contain 'project_id'
```

Removing the top level `projectID` from the manifest JSON of this modpack fixes the issue.

**Comment by Danacus** [comment]
After installing version 1.0.5 first, I am suddenly able to install the hotfix. A bit weird, but I guess I can close this issue.

**Comment by TheStaticVoid** [comment]
Strange, that file is built from packwiz and I've never had that issue before. I'll keep an eye out for any other oddities in the future.

**Comment by Danacus** [comment]
It might also be a bug in Prism Launcher.

By the way, another unrelated problem I encountered when trying to use the hotfix is that I can't load any existing worlds because you appear to have accidentally removed Terralith.
