### ISSUE TITLE
Dank, no recipe

### ISSUE THREAD

**Issue by hgjensen** [TheStaticVoid/StaTech-Industry#263]
Dank Storage seems to be in the pack, but no recipes for any of the items.

**Comment by TheStaticVoid** [comment]
Make sure it's installed on the server-side as well

**Comment by hgjensen** [comment]
> Make sure it's installed on the server-side as well

I see. Thank you.
I would have imagining it would have been included in the official server installer? - especially seeing as it is in the client.

**Comment by TheStaticVoid** [comment]
it was a mistake this patch, will be addressed in next patch
