### ISSUE TITLE
Quest for Chlorine Bucket references previous chapter despite no previous mention of any steps of the process

### ISSUE THREAD

**Issue by BadCoder2** [TheStaticVoid/StaTech-Industry#265]
The Chlorine Bucket quest (shortly after Large Components, after Electrolyzer) has the following text:
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/46334485/35c2f020-7ad6-4dde-a739-2c95c7cb6802)
This is the first appearance of salt and chlorine, and the electrolyzer is a prereq. for this quest. As such the text doesn't really make sense.

**Comment by TheStaticVoid** [comment]
I might of had this in the HV chapter awhile back and moved it then forgot to change it's text. Will be updated in 1.0.6
