### ISSUE TITLE
Remove "A Terralith Skill Issue" Quest

### ISSUE THREAD

**Issue by truepurpledino** [TheStaticVoid/StaTech-Industry#269]
Since the removal of Terralith, Quitoxic reeds generate naturally so the quest isn't necessary anymore.

**Comment by TheStaticVoid** [comment]
I forgot these thanks

**Comment by truepurpledino** [comment]
Might as well add the "Another Terralith Skill Issue" to the list

**Comment by TheStaticVoid** [comment]
I already got the mermaid gem one as well
