### ISSUE TITLE
missing items/tags for chapter 1 "hammers" and utilities "spice of life containers"

### ISSUE THREAD

**Issue by gildervine** [TheStaticVoid/StaTech-Industry#295]

**Comment by TheStaticVoid** [comment]
Not sure what you mean?

**Comment by gildervine** [comment]
![grafik](https://github.com/TheStaticVoid/StaTech-Industry/assets/81438399/b1ed1372-51a2-466c-8c37-19a179249845)
![grafik](https://github.com/TheStaticVoid/StaTech-Industry/assets/81438399/1dea9490-c487-4e43-891b-ec0ba8e4dbed)

**Comment by TheStaticVoid** [comment]
I can't help unless you post your logs

**Comment by TheStaticVoid** [comment]
Could you also upload your `kubejs/server_scripts.log` file?

**Comment by gildervine** [comment]
https://pastebin.com/s1LVEZkg
![png](https://github.com/TheStaticVoid/StaTech-Industry/assets/81438399/4e86b916-f977-4dae-ba3b-fa7d90443a6e)

**Comment by TheStaticVoid** [comment]
This is a known issue with Rhino with KubeJS. The only solution I know of is just running `/reload` to fix it. There's nothing I can do on my side.

**Comment by GW-Dev** [comment]
Hey isn’t there [This](https://discord.com/channels/754461970870173767/760125612126896196/1114867155448647831) hacky workaround from the MI discord?

**Comment by TheStaticVoid** [comment]
AFAIK that was mainly to fix issues with item tags not getting applied or working properly on server startup. While it might fix this issue, this ISE has been pretty random and forcing a reload will cause longer loadtimes.
