### ISSUE TITLE
1.1.2 Update Ore veins is too huge 

### ISSUE THREAD

**Issue by Hal0gen3s** [TheStaticVoid/StaTech-Industry#311]
Ore veins too huge this maybe not a issue, You know GTNH ore veins is not larger than 3x3 chunks but in StaTech the chunk i found larger than 3x3 chunks 

![Ekran görüntüsü 2023-07-29 225143](https://github.com/TheStaticVoid/StaTech-Industry/assets/140916703/54ce9912-02b4-43cf-b0b5-ca033dc152d2) <--- this a single vein a I found

**Comment by TheStaticVoid** [comment]
1. This is not GTNH
2. The purpose of veins is to make the player find individual nodes for resources. These nodes should last you awhile, even up until the Quarry.
