### ISSUE TITLE
"The Coke Oven" quest is missing valid items to complete

### ISSUE THREAD

**Issue by FritzX43** [TheStaticVoid/StaTech-Industry#321]
The item input, item output, and fluid input task do not have items to mark them as complete thus making the entire quest impossible to complete

**Comment by TheStaticVoid** [comment]
Those parts of the task should be accepting of any block with the corresponding tag. What version are you on?

**Comment by FritzX43** [comment]
i just updated to 1.1.3 but i noticed a similar thing happening in 1.1.2. I looked around the quest and it seems to be an issue with all quest requiring hatches

**Comment by TheStaticVoid** [comment]
Can you send the `server.log` file in your `logs/kubejs` folder

**Comment by FritzX43** [comment]
[server.log](https://github.com/TheStaticVoid/StaTech-Industry/files/12209985/server.log)

**Comment by TheStaticVoid** [comment]
Please delete your `kubejs` folder and reinstall the pack. It looks like whatever launcher you are using did not remove the files between updates and it's causing errors from mods that have been removed.

**Comment by FritzX43** [comment]
thank you, that seems to have fixed it
