### ISSUE TITLE
Tom's storage fluid dupe with MI tanks

### ISSUE THREAD

**Issue by AyAyEm** [TheStaticVoid/StaTech-Industry#333]
When there's one tank with any amount of a certain fluid, inside a Tom's Simple storage system, putting more tanks of the same tier but empty inside the system makes them have the same amount of the said fluid.

My system is hooked up create vault's and some drawers, i didn't test all the possibilities and i'm not sure if it's possible to reproduce in other worlds, in any case it seems like a problem between the Tom's storage system and Modern Industrialization.

At the time of writing, i'm using the version 1.1.3 of the modpack (without any changes to MI or Tom's storage).

**Comment by TheStaticVoid** [comment]
I can't reproduce this, could you provide some more details or an image of your setup?

**Comment by AyAyEm** [comment]
I hope this helps https://youtu.be/R8oOB3lAV1g

**Comment by TheStaticVoid** [comment]
This is probably never getting fixed 💀
