### ISSUE TITLE
MI Alloy Smelter Iron Block + Nickel Block = Nickel Block

### ISSUE THREAD

**Issue by AyAyEm** [TheStaticVoid/StaTech-Industry#337]
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42449362/bf8be871-b574-4fa2-83c3-dd8329603deb)
I think it should be 4 invar blocks as a result. Not 4 nickel blocks.

**Comment by TheStaticVoid** [comment]
that's correct, it's a typo
