### ISSUE TITLE
Tech Reborn no way to craft small pile of obsidian dust

### ISSUE THREAD

**Issue by AyAyEm** [TheStaticVoid/StaTech-Industry#344]
Shoudn't we be able to craft 4 small pile of obsidian dust from one obsidian dust?

Currently the only way to get it:
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42449362/685e6bd8-e071-47a1-8dc2-81e1d3f627c8)

**Comment by TheStaticVoid** [comment]
Ahh, I forgot this was used in the marble recipe. All the small pile recipes were removed due to conflicts with MI ones when it came to compacting drawers. I'll add something to fix this.

**Comment by AyAyEm** [comment]
Maybe just grind the marble from the blockus mod

**Comment by TheStaticVoid** [comment]
That's what I was thinking
