### ISSUE TITLE
Waystones duplicating with Steam Mining Drill

### ISSUE THREAD

**Issue by JannersLSR** [TheStaticVoid/StaTech-Industry#356]
Tried on different waystones and they still work. MI hammers don't dupe it only the Steam Mining Drill.
Either the top or the bottom part of the waystone dupes it. 

Tested on version 1.1.2. haven't tested on newer versions.

[Waystone Dupe](https://streamable.com/kmger0) (ignore the discord sounds lol)

**Comment by TheStaticVoid** [comment]
Known issue with the fabric library. Nothing I can do to fix this tbh.
