### ISSUE TITLE
Several quests in "World of Magic" chapter has wrong achievements as a tasks.

### ISSUE THREAD

**Issue by Janitor53** [TheStaticVoid/StaTech-Industry#358]
Version 1.1.5 hotfix
Quests "The Mixing Ruins", "CMY pedestal variant", "The Dike Ruins", "The Bedrock Ruins" all has "Centennial" advancement as a task. IDK where from this achievement is but it is totally unrelated to quests.

**Comment by TheStaticVoid** [comment]
I can't replicate this. Can you send your latest.log or kubejs logs?

**Comment by Janitor53** [comment]
Latest.log: https://mclo.gs/k1xDuMw
[client.log](https://github.com/TheStaticVoid/StaTech-Industry/files/12268822/client.log)
[server.log](https://github.com/TheStaticVoid/StaTech-Industry/files/12268823/server.log)
[startup.log](https://github.com/TheStaticVoid/StaTech-Industry/files/12268824/startup.log)

**Comment by Janitor53** [comment]
Sorry for false alarm, I found the cause. I accidentally upgrade Spectrum mod to latest alpha. Some advancements were renamed there.
