### ISSUE TITLE
Incorrect Sheldonite ore recipe in large steam macerator

### ISSUE THREAD

**Issue by truepurpledino** [TheStaticVoid/StaTech-Industry#391]
Sheldonite is 1 ore to 24 raw platinum in the recipe for large steam macerator in version 1.1.6. It should be 8 ore to 24 raw platinum.
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/75775263/6aded9ff-1276-40fe-9d57-f95bdc342139)

**Comment by TheStaticVoid** [comment]
Also applies to the following:

- Zinc Ore
- Deepslate Zinc Ore
- Deepslate Sheldonite Ore
- Raw Zinc
