### ISSUE TITLE
"Incompatible mod set" after updating from 1.1.5 hotfix to 1.1.6 on Prism Launcher 7.2

### ISSUE THREAD

**Issue by lolghurt** [TheStaticVoid/StaTech-Industry#393]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install resourcefullib, version 1.1.23 or later.
	 - Install botarium, version 1.8.2 or later.
	 - Install ae2, version 12.8.4 or later.
	 - Install geckolib3, version 3.1.40 or later.
	 - Install corgilib, version 1.0.0.34 or later.
	 - Install trinkets, any version.
	 - Install balm-fabric, version 4.0.0 or later.
	 - Install collective, version 6.62 or later.
	 - Install farmersdelight, any version.
	 - Install ftblibrary, version 1902.4.1-build.236 or later.
	 - Install configured, any version between 2.0 (inclusive) and 3- (exclusive).
	 - Install libipn, any version between 3.0.2 (inclusive) and 4.0.0 (exclusive).
	 - Install wthit, version 5.17 or later.
	 - Install roughlyenoughitems, version 9.1 or later.
	 - Install owo, any version.
	 - Install bookshelf, version 16 or later.
	 - Install supermartijn642corelib, any version between 1.1.0 (inclusive) and 1.2.0 (exclusive).
	 - Install supermartijn642configlib, version 1.1.0 or later.
	 - Install spell_engine, version 0.9.21+1.19 or later.
	 - Install spell_power, any version.
Unmet dependency listing:
	 - Mod 'Ad Astra' (ad_astra) 1.12.7 requires version 1.1.23 or later of resourcefullib, which is missing!
	 - Mod 'Ad Astra' (ad_astra) 1.12.7 requires version 1.8.2 or later of botarium, which is missing!
	 - Mod 'AE2WTLib' (ae2wtlib) 12.9.5 requires version 12.8.4 or later of ae2, which is missing!
	 - Mod 'Simple Animated Guns' (animated_guns) 1.2 requires version 3.1.40 or later of geckolib3, which is missing!
	 - Mod 'Oh The Biomes You'll Go' (byg) 2.0.1.4 requires version 1.0.0.34 or later of corgilib, which is missing!
	 - Mod 'Oh The Biomes You'll Go' (byg) 2.0.1.4 requires version 3.1.25 or later of geckolib3, which is missing!
	 - Mod 'Charm of Undying' (charmofundying) 6.2.1+1.19.2 requires any version of trinkets, which is missing!
	 - Mod 'Crafting Tweaks' (craftingtweaks) 15.1.8 requires version 4.0.0 or later of balm-fabric, which is missing!
	 - Mod 'Double Doors' (doubledoors) 5.0 requires version 6.62 or later of collective, which is missing!
	 - Mod 'Expanded Delight' (expandeddelight) 0.2.5.2 requires any version of farmersdelight, which is missing!
	 - Mod 'Farming for Blockheads' (farmingforblockheads) 11.3.1 requires version 4.0.0 or later of balm-fabric, which is missing!
	 - Mod 'FTB Chunks' (ftbchunks) 1902.4.1-build.290 requires version 1902.4.1-build.236 or later of ftblibrary, which is missing!
	 - Mod 'FTB Teams' (ftbteams) 1902.2.14-build.123 requires version 1902.3.10-build.159 or later of ftblibrary, which is missing!
	 - Mod 'FTB Essentials' (ftbessentials) 1902.3.3-build.100 requires version 1902.3.16-build.191 or later of ftblibrary, which is missing!
	 - Mod 'Goblin Traders' (goblintraders) 1.8.1 requires any version between 2.0 (inclusive) and 3- (exclusive) of configured, which is missing!
	 - Mod 'Inventory Profiles Next' (inventoryprofilesnext) 1.10.6 requires any version between 3.0.2 (inclusive) and 4.0.0 (exclusive) of libipn, which is missing!
	 - Mod 'KleeSlabs' (kleeslabs) 12.3.0 requires version 4.0.0 or later of balm-fabric, which is missing!
	 - Mod 'megane' (megane) 8.5.0 requires version 5.17 or later of wthit, which is missing!
	 - Mod 'Naturalist' (naturalist) 3.0.4 requires version 3.0.0 or later of geckolib3, which is missing!
	 - Mod 'Passive Shield' (passiveshield) 3.2 requires version 6.45 or later of collective, which is missing!
	 - Mod 'Roughly Enough Trades' (roughly_enough_trades) 1.19-1.0 requires version 9.1 or later of roughlyenoughitems, which is missing!
	 - Mod 'Spectrum' (spectrum) 1.6.12-1.19.2-leisure_time requires any version of owo, which is missing!
	 - Mod 'Spectrum' (spectrum) 1.6.12-1.19.2-leisure_time requires any version of trinkets, which is missing!
	 - Mod 'Superflat World No Slimes' (superflatworldnoslimes) 3.0 requires version 6.7 or later of collective, which is missing!
	 - Mod 'ToolStats' (toolstats) 12.1.4 requires version 16 or later of bookshelf, which is missing!
	 - Mod 'Wireless Chargers' (wirelesschargers) 1.0.9 requires any version between 1.1.0 (inclusive) and 1.2.0 (exclusive) of supermartijn642corelib, which is missing!
	 - Mod 'Wireless Chargers' (wirelesschargers) 1.0.9 requires version 1.1.0 or later of supermartijn642configlib, which is missing!
	 - Mod 'Wizards' (wizards) 0.9.17+1.19 requires any version of geckolib3, which is missing!
	 - Mod 'Wizards' (wizards) 0.9.17+1.19 requires version 0.9.21+1.19 or later of spell_engine, which is missing!
	 - Mod 'Wizards' (wizards) 0.9.17+1.19 requires any version of spell_power, which is missing!
	 - Mod 'megane-runtime' (megane-runtime) 8.5.0 requires version 5.17 or later of wthit, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by lolghurt** [comment]
It appears that for whatever reason, a large number of mods aren't being fetched correctly by prism launcher anymore.

**Comment by TheStaticVoid** [comment]
This is a common issue with Prism with this update. I would recommend creating a new instance and copying over your save, options.txt, rei config (for bookmarks) and journeymap folder over into the new instance.

**Comment by lolghurt** [comment]
Thanks, this appears to have worked
