### ISSUE TITLE
How to properly update the modpack (Client + Server)?

### ISSUE THREAD

**Issue by zippoking** [TheStaticVoid/StaTech-Industry#399]
Hey,

i am absolutely loving your modpack so far. I started playing on 1.1.6. Now that you released 1.1.7 i was wondering how to properly update a modpack? I have actually never done that.
So how do i update the client? How do i update the server? Does that interfere with configs that i changed? 
Or what if i added another mod? Does everything reset?

Hope you can help me out and explain to me what i should do. 

Thanks in advance!

Best regards
Zippoking
PS: i am using the PrismLauncher

**Comment by TheStaticVoid** [comment]
For the client, there's been issues with updating the existing instance for some. At this point I recommend creating a new instance for the pack and copying over your options.txt and journeymap folder.

As for the server, you only really need to delete the ftbqueste config folder and install the updated version. For mods I would recommend pulling any jars you've added into another folder, delete all the others, install the jars from the update and reinstall whatever else you had manually added.

**Comment by zippoking** [comment]
Alright, thanks for the quick response. I will try that.

Modded Minecraft needs a better way for updates :-D
