### ISSUE TITLE
Pocket Crafting Table not working

### ISSUE THREAD

**Issue by DFreezerR** [TheStaticVoid/StaTech-Industry#423]
Just downloaded a modpack. And 10 minutes in I made a Pocket Crafting Table for quest and it seems to be broken. Recipes just not working. Even basic stuff like wood -> planks can not be done. 

Some additional info below:
<details>
  <summary>Example recipes</summary>
  
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/60145703/f93f63c0-d9aa-4ace-b972-23b0de472f22)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/60145703/c4a4ea64-cd34-4d5d-8d75-0619bd1e2b7e)

</details>
<details>
  <summary>Start-up logs recorded until a bug (I hid user/login info just in case)</summary>
[logs.txt](https://github.com/TheStaticVoid/StaTech-Industry/files/12480571/logs.txt)

</details>

- Java version video driver and OS might be seen in logs above (if needed)
- Modpack version 1.1.8
- Last time I played this modpack on 1.1.4hotfix version and that time pocket crafting table was working.
- It's almost a clean modpack install (added Iris on top of included mods). I deleted last modpack I had and download a newer one so I doubt I messed something up with file system

**Comment by truepurpledino** [comment]
I believe the mod FastBench causes this issue, you can safely remove it from the pack. It will also be removed as of next update.

**Comment by DFreezerR** [comment]
> I believe the mod FastBench causes this issue, you can safely remove it from the pack. It will also be removed as of next update.

Yes, FastBench is the issue. Just disabled it and everything is working now. 👍
