### ISSUE TITLE
Ringing bells in villages consistently crashes the game

### ISSUE THREAD

**Issue by EntityinArray** [TheStaticVoid/StaTech-Industry#443]
Ringing bells in villages crashes the game every time
Apparently caused by foundationgames.enhancedblockentities
Crash log: https://pastebin.com/jKCwGZzN

Video that demonstrates the crash:
https://files.isekai.su/statech_bell_bug.mp4

Statech Industry 1.1.9

Tell me if any other info is needed, thank you!

**Comment by TheStaticVoid** [comment]
Looks like it's caused by EnhancedBlockEntities. There are settings in the `enhanced_bes.properties` file in the `config` folder related to bells. Could you try setting `render_enhanced_bells` to `false` and see if that fixes the issue?

**Comment by EntityinArray** [comment]
Yes, no more crashing with `render_enhanced_bells` in `config/enhanced_bes.properties` set to false

**Comment by TheStaticVoid** [comment]
Alright I went ahead and set it to false in the pack as well

**Comment by EntityinArray** [comment]
I figured out the cause of the crash. Default install of Statech Industry doesn't crash out of the box, this crash only occurs with Iris with any shaders on.
I think we could keep enhanced bells disabled until they fix compatibility with shaders

**Comment by TheStaticVoid** [comment]
The performance impact of having this setting to false is probably insanely minimal. It would be better to avoid having a potential crash rather than maybe save ~1fps
