### ISSUE TITLE
Crash when interacting with pigment pedestal

### ISSUE THREAD

**Issue by shinji257** [TheStaticVoid/StaTech-Industry#444]
One of the players on my server managed to crash it while interacting with a pigment pedestal.  Not sure how exactly it happened but the steps that I was told was that they had placed the item into it and it crashed then with a Ticking Block Entity notification in the crash log.  They were attempting to craft a Crafting Tablet so they were at the 3rd quest.

I had to replace the block with cobblestone using worldedit so that the chunk could be properly loaded again.  Unfortunately I tried to reproduce it myself and wasn't able to do so in a personal test single player world or server.  Regardless I'm reporting this incase anyone else gets this issue and is able to provide more insight.

https://gist.github.com/shinji257/b3c1f5d1e6df4e37a07b5adc2948d484

**Comment by TheStaticVoid** [comment]
Hmm I've never seen something like this before. I will have to look into some of those class mappings and Spectrum src code to see where exactly it's failing. This should probably not happen again, as it seems like a rare edge case.

**Comment by shinji257** [comment]
That's what I'm hoping but it is an edge case that drops the server when the chunk loads.  Thanks for looking into it.

**Comment by shinji257** [comment]
Players decided to push it and try it again.  Same crash happened again so not sure what causes it for sure.

https://gist.github.com/shinji257/9181f24efe1866ce5894045ccf325cfc

**Comment by shinji257** [comment]
Figured out the cause.  It's our own item blacklist mod.  We will sort that out but still not sure why it only happened with Spectrum.  There is definitely an interaction bug happening somewhere.  Currently the blacklist mod isn't even configured to blacklist anything.

**Comment by TheStaticVoid** [comment]
Which mod was it?

**Comment by shinji257** [comment]
It's this one: https://www.curseforge.com/minecraft/mc-mods/item-banning-fabric

**Comment by TheStaticVoid** [comment]
Ah seems like a low download mod that probably hasn't tested its compatibility. Might be worth letting that mod author know.
