### ISSUE TITLE
Problem with Annealed Copper Hot Ingot (Version 1.1.9)

### ISSUE THREAD

**Issue by Nogapra** [TheStaticVoid/StaTech-Industry#447]
Hello

in version 1.1.9 of the modpack, I can't make Annealed Copper Hot Ingot.

In Electrical Age Quest:

I have an EBF in Kanthal Coils and it is powered by MV electricity with 9 Advanced Upgrade, I put oxygen but the quest says that it is necessary to mix Oxygen with Copper Ingots but REI shows the craft with Copper Dust and Oxygen, but none of the 2 ways to do it works

![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/937717bb-19c6-4425-a34c-66d7c9b2a5e1)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/edd922e7-6de2-48b4-b98c-64107d8a33c9)

**Comment by TheStaticVoid** [comment]
Did you have any error messages in the chat when you joined the world? It happens sometimes that KubeJS has a tag issue that you need to reload to fix some issues. If you're not sure, just post your `latest.log`

**Comment by truepurpledino** [comment]
The recipe works just fine in my instance of 1.1.9. Make sure that the multiblock :

- has an item output hatch (that has space for the hot ingot)
- has a fluid input hatch (with oxygen)
- has an item input hatch (with copper dust)
- has power (make sure if you are giving it MV power, that it is through a MV energy input hatch, not a LV one)
- is valid (check with a wrench, then in the interface, where it should show you to choose either if it is a cupronickel or kanthal EBF)

I think this last one is probably the one you might be doing wrong, see this screenshot :
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/75775263/55fbb7e5-d05f-4fd0-9914-4bb6bfc852c4)

**Comment by Nogapra** [comment]
I play on server and I have no error message from KubeJS to be sure I made a /reload in the server console I got the message of the reload without error

I locked the craft thanks to REI by clicking on the black part of the controller and then on the plus sign to lock the inputs and outputs on the craft components. 

Either for REI: 
- Copper dust as input in the Steel Item Input Hatch
- Oxygen input Fluid Input Hatch

- and Annealed Copper Hot Ingot on the Steel Item Output Hatch

![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/4d468c85-4693-4c23-b0e5-fc897a6d45ba)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/cdf7ef5e-5690-48a0-a0f6-aa2cb75f97e6)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/2b110168-4ae7-4183-bd5c-38deb87a3129)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/f0519577-caf7-4dad-b0f3-f02ccb202eab)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/b122917f-326f-40b9-ba91-8c0534e507fa)
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/79e4f752-a4d4-41a7-8cb5-aef0262b21a1)

Link pastebin for the latest log server : https://pastebin.com/ecpKPGbZ

**Comment by Nogapra** [comment]
On the other hand I do not see the connection with a probable problem with KubeJS because when I do a search on all the files that come from the archive that I just recovered on GitHub I do not see any reference between the Annealed Copper Hot Ingot and the EBF so I do not understand ^^

![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/42911787/5df70f65-bb4c-4a66-aab9-a9a6c013808e)

**Comment by TheStaticVoid** [comment]
the json file for the ingot appears to be missing from the data folder

**Comment by Nogapra** [comment]
So the JSON file is also manquand in version 1.1.7 and 1.1.8

**Comment by TheStaticVoid** [comment]
The file is in the last update (1.1.9), something might have happened during your install
https://github.com/TheStaticVoid/StaTech-Industry/blob/2ad09fa3b627511723dcae07ae4f71abdc871580/kubejs/data/modern_industrialization/recipes/materials/kanthal/blast_furnace/dust.json

**Comment by Nogapra** [comment]
humph
The problem does not come from Kanthal's dust but from the annealed copper hot ingot

**Comment by TheStaticVoid** [comment]
The next update moves all the datagen to a .zip so hopefully it fixes your issue

**Comment by Nogapra** [comment]
A release date of the Maj ??

**Comment by TheStaticVoid** [comment]
I just pushed it to GitHub, it's awaiting approval on Curseforge currently

**Comment by Nogapra** [comment]
on the other hand it does not tell me why the craft of REI is different from the one mentioned in the quest, so what the ingot it will have to be done with a copper dust or with a copper ingot ??

**Comment by TheStaticVoid** [comment]
It should be copper dust + oxygen -> hot annealed copper ingot

**Comment by Nogapra** [comment]
I downloaded the archive of the 1.1.10 directly on the GitHub, I unzipped the archive and recovered the files in the archive that was in KubJS I transferred it to my server made a /reload in server console and the it works weird in any case thank you for the time given to my worries you can close the problem

Nice Work
