### ISSUE TITLE
Random problem with emojiful in client

### ISSUE THREAD

**Issue by Nogapra** [TheStaticVoid/StaTech-Industry#448]
Randomly since version 1.1.9 when I enter an interface, I have the client crashing. 
I specify that I play on a hosted server and not locally and I do not know if it does the same thing partly locally, I disable the mod and, in the client, and the server and I no longer have the problem Pastebin link of the crash report.

It doesn't seem to me that this is an important mod for the gameplay, so it doesn't matter but it was just to warn you ^^
Link: https://pastebin.com/UxMS2XnQ

**Comment by TheStaticVoid** [comment]
This is a known issue with fastutil, no fix at this time

**Comment by Nogapra** [comment]
Ok
