### ISSUE TITLE
Missing Bottle of failing recipe in Spectrum

### ISSUE THREAD

**Issue by Puniek** [TheStaticVoid/StaTech-Industry#450]
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/24876906/c9310ec9-f661-4001-b556-15cc109ea771)
Along with many others in 1.1.10. Command `/spectrum-sanity` lists tonnes of them.

**Comment by TheStaticVoid** [comment]
Did you have any error messages in chat when joining the world. I'm going to guess that it's probably the KubeJS tag error causing recipes to not load correctly. Check our `logs/kubejs/server.log` file and post it here.

**Comment by Puniek** [comment]
Nope, no errors with kubejs, also not getting any errors in chat when logging in.
[server.log](https://github.com/TheStaticVoid/StaTech-Industry/files/12672943/server.log)

**Comment by Puniek** [comment]
It reloaded with no errors, but the sanity checks on the spectrum mod still shows the missing advancement to unlock the recipe.

**Comment by TheStaticVoid** [comment]
Well the recipe id in your initial post is a randomly generated one, which shouldn't happen as every custom recipe in spectrum has an id. Something may be wrong with your installation, as the error is specifically saying it can't find the advancement, which is impossible if Spectrum is installed.

**Comment by Puniek** [comment]
Did a bit more digging. One of the admins updated spectrum to higher version, which changed internally some advancement ids. So a false alarm and a thing to think about if you get to update the Spectrum in future - it will require some migration code for the changes to not break the progress on existing worlds.
