### ISSUE TITLE
Building Gadgets crash when opening material list

### ISSUE THREAD

**Issue by Puniek** [TheStaticVoid/StaTech-Industry#455]
When trying to open a material list for a template in Copy/Paste Gadget, whole client crashes.

Running 1.1.10 on Server and Client.

**Comment by TheStaticVoid** [comment]
Known issue with the mod. I think someone in the Discord found a workaround.

**Comment by Puniek** [comment]
For others that might be looking for a solution:
`If you want to see the material list, once you copy a selection hold shift and hover over the copy-paste tool in your inventory, or use a template table to copy the template to your clipboard, paste it in note pad, and the materials are toward the top`
