### ISSUE TITLE
Add recipes for various TR items in MI machines

### ISSUE THREAD

**Issue by truepurpledino** [TheStaticVoid/StaTech-Industry#465]
Various items from TR cannot be crafted in MI machines. Here are the items and what machine I suggest adding a recipe for them:

- Mixed Metal Ingots (packer)
- Superconductor (assembler)
- 60k Helium Coolant Cell (assembler with helium as liquid)
- Digital Display (assembler)
- Basic Machine Frame (assembler)
- Advanced Machine Frame (assembler)
- Industrial Machine Frame (assembler)
- Lapotronic Energy Orb (assembler)
- Ajustable SU (assembler)
- 10k Water Coolant Cell (assembler with water as liquid)
- Overclocker Upgrade (assembler)

Most of these are just for QOL and are components of other crafts.

**Comment by GW-Dev** [comment]
I started working on this and can hop back on it if Static wants.

**Comment by TheStaticVoid** [comment]
have at it if you want

**Comment by TheStaticVoid** [comment]
There's a good chance TR is going to be removed entirely for this update so I'm going to put this on hold for now.
