### ISSUE TITLE
How can we automate the recovery of certus quartz? (Help Wanted)

### ISSUE THREAD

**Issue by Nogapra** [TheStaticVoid/StaTech-Industry#466]
Hello

How can we automate the recovery of certus quartz?
Because to use the mob crusher and the boss crusher we need creature models that are made with advanced cards or basic cards which are themselves made with calculations processors.

So we need to recover a lot of certus quartz to automate the Impure liquid nether star for the superconductor ingot as well as for the ender pearl for the Molten enderium among others.

Kind regards

**Comment by TheStaticVoid** [comment]
You can find pure budding certus quartz blocks in the meteors from AE2 that grow certus crystals over time. They can be moved with Create contraptions back to your base, or you can automate the creation of flawed budding certus quartz using the tiered recipe in the mixer.

**Comment by Nogapra** [comment]
Hello

I understood this part on Applied Energestics 2 but the problem is that there is no way to break the Certus Quartz other than with a pickaxe in our hand to recover a large amount of it.

However, according to the consumption calculations of the models in the machine wither skeleton model = 4% chance of being consumed and only 2.5% drop rate for a head (same drop rate as vanilla Minecraft without looting)

So to have 250 heads of Wither Skeleton you will have to count on a probable loss of 400 Wither Skeleton Model 

250 heads of wither skeleton gives only 83 Withered SoCs or 83 wither models that have a 100% chance of being consumed. These 83 wither models will only give 41500 MB of Impure Liquid Nether Star or 830 Supercondutor Ingot so 3318 Superconductor Cable.

Having to harvest certus quartz by hand is not very practical.

I can't seem to find a way to automatically break (either by modern industrialization or by Create or tech reborn) the certus quartz from the budding certus quartz
Kind regards

**Comment by WaterFace** [comment]
You can use AE2's annihilation planes to automate certus quartz. The documentation has a detailed example: https://guide.appliedenergistics.org/#/1.20.1/ae2:example-setups/advanced-certus-farm.md

**Comment by Nogapra** [comment]
Nice, thanks you
