### ISSUE TITLE
Missing assembler/packer recipes

### ISSUE THREAD

**Issue by Luligabi1** [TheStaticVoid/StaTech-Industry#469]
Just some stuff I'd like seen automatable through MI 🙂 

- Vanilla Pistons
- Dense cables
- Formation/annihilation core
- ME Storage, Export and Import Buses

**Comment by GW-Dev** [comment]
Anything else? I can add these to my recipe tweaks PR.

**Comment by Luligabi1** [comment]
> Anything else? I can add these to my recipe tweaks PR.

Hmm, not that I'm remembering right now. There might be other AE2 components that others would like automatable too, but I'm not well versed enough on the mod to know 😅
