### ISSUE TITLE
Bug: Game crashes when opening quests whilst in Crafting Calculator GUI

### ISSUE THREAD

**Issue by KThompson-Lane** [TheStaticVoid/StaTech-Industry#471]
## Description:
When you try to open the quests from the widget within NEI whilst having the Crafting Calculator open the game crashes to desktop.

## Reproduction steps:
1. Right click the crafting calculator to open the GUI
2. Left click the quests widget in the top left of the NEI interface

### Expected outcome:
FTB quests are shown as normal
### Actual outcome:
Game crashes to desktop

### Affected versions:
Reproducible on 1.1.10 and 1.1.11, not attempted to reproduce on other versions.

**Comment by TheStaticVoid** [comment]
This is an issue with the calculator / FTB quests mod, not the pack itself. Please report the issue to respective mod owners.
