### ISSUE TITLE
Industrial Greenhouse

### ISSUE THREAD

**Issue by SkyhojeChed** [TheStaticVoid/StaTech-Industry#473]
Hello. There was a problem with the "nutrient" liquids in the greenhouse. None of the following liquids: nutrient rich water, nutrient rich blood, nutrient rich fender are used, but they are mentioned in the recipe. I tried different configurations of "greenhouse" and plants. Only ordinary liquids are used: water, blood, liquid ender.
![greenhouse](https://github.com/TheStaticVoid/StaTech-Industry/assets/159958344/aa486f57-2d9f-4351-82f7-f1a84dce179c)

**Comment by truepurpledino** [comment]
How many and what kind of output hatches do you have? Using nutrient rich water requires you to have at least 3 output slots, so if you are not using a advanced output hatch or two steel hatches, the recipe won't work.

**Comment by truepurpledino** [comment]
When using water, the recipe works because the third (sapling) output is a chance output, therefor it doesn't care to have a specified output slot since it will just void it.

**Comment by SkyhojeChed** [comment]
How simple it turned out to be..... I added a second exit hatch, and everything worked. Sorry for wasting your time P-P
