### ISSUE TITLE
Game crashes when interacting with Mechanical Mixer recipe in REI

### ISSUE THREAD

**Issue by fukudck** [TheStaticVoid/StaTech-Industry#477]
## Crash logs: 
https://mclo.gs/k9zQFTR
## Video that demonstrates the crash: 
https://youtu.be/bdnJRWPro4Y
## Version:
StaTech Industry 1.1.12

It only crashes when you hover your mouse to item. Sometimes yes, sometimes no

**Comment by TheStaticVoid** [comment]
This is a currently known issue with Create. You can downgrade the Create version in your install while I wait for the fix to be released for 1.19.2 Create.

**Comment by Ricket** [comment]
It's a consistent crash for me, if I look up the recipe for Bronze Ingot, go to Mixer tab, and hover the Raw Tin item.

I fixed it by building Create from the 1.19 branch except it still needed an additional codefix, I just opened a bug report: https://github.com/Fabricators-of-Create/Create/issues/1382

**Comment by fukudck** [comment]
@Ricket Thanks a lot.
Fixed at https://github.com/Fabricators-of-Create/Create/commit/2551fd4a5d508bb2d5e0a76ac4fe9e9fce91428b

**Comment by TheStaticVoid** [comment]
Reopening so that duplicates don't get created

**Comment by Wyrmlet** [comment]
Same issue, just ran into this myself. Do all recent versions of create cause this crash?
https://mclo.gs/v3e7of9

**Comment by TheStaticVoid** [comment]
it is fixed in their development branch, which you can build yourself manually or wait until they release an official version

**Comment by Wyrmlet** [comment]
Yeah, I'll give that a go, thank you.

**Comment by Wyrmlet** [comment]
None of the create versions of create 1.19 seem to compile out of the box (maybe it's just my setup being weird), but an alternative solution is to replace REI with JEI, as this is one of the mods that causes the crash.

**Comment by TheStaticVoid** [comment]
Fixed in future 1.1.13 release
