### ISSUE TITLE
Item dupe with Tom's simple storage

### ISSUE THREAD

**Issue by Wyrmlet** [TheStaticVoid/StaTech-Industry#483]
I am using the most recent version of the pack at the time of writing, I think. It seems like just taking an item from the inventory system has a chance of duping it! After a bit of testing it seems like this is caused by an interaction between a trim and a create chute, as removing it seems to stop this from happening.
More specifically, I have a setup with two gold chests stacked on top of each other with a chute in between, all of that connected to the inventory system with trims.

**Comment by TheStaticVoid** [comment]
Tom's is unfortunately abusable, and this isn't the first dupe that's been found. The mod has been updated and claims to fix some dupes so we'll see what happens in 1.1.13
