### ISSUE TITLE
Recipe HUD Crash

### ISSUE THREAD

**Issue by Hal0gen3s** [TheStaticVoid/StaTech-Industry#484]
I open on the REI and game crashed

[crash-2024-04-03_20.18.28-client.txt](https://github.com/TheStaticVoid/StaTech-Industry/files/14856138/crash-2024-04-03_20.18.28-client.txt)

**Comment by CesarSarantakos** [comment]
"IThundxr
known issue fixed in dev"

https://github.com/Fabricators-of-Create/Create/issues/1380

**Comment by CesarSarantakos** [comment]
Removing REI and replacing it with EMI solves it. Im trying to figure out how to solve the quest book problem now, it simply doesnt open

**Comment by TheStaticVoid** [comment]
Fixed in future 1.1.13 release
