### ISSUE TITLE
No recipe for Kibe tank

### ISSUE THREAD

**Issue by dhasial** [TheStaticVoid/StaTech-Industry#492]
This is an issue not just becaue the tank is unavailable, but because it is part of the recipe for Coxinha Utilities "MK1 tank", which in turn is required for the Coxinha Utilities "Fluid Trashcan".

The only recipes for the tank are the Create "Filling by Spout" ones.

StaTech Industry 1.1.13

**Comment by TheStaticVoid** [comment]
The recipe was deliberately removed as the pack urges for the usage of MI tanks. I'm not familiar with this Coxinha Utilities, and am assuming it's another mod which is not in the pack. You can modify the kibe.js file removing the recipe if you would like them back in your install if you plan to play with that mod.
