### ISSUE TITLE
Can't automate the crafting of Molten Enderium with AE2

### ISSUE THREAD

**Issue by AlexDiego123** [TheStaticVoid/StaTech-Industry#499]
I can't automate the crafting of Molten Enderium with AE2 because there's _apparently_ no way to input the items and fluids into two different hatches (item and fluid input hatch) with one ME pattern provider, i already tried connecting some pipes to the pattern provider or placing two of them in each of the hatches but it doesn't work. How do i fix this? I already tried searching mods that have like a buffer block that can hold items and fluids at the same time so i can then output the contents in the respective hatches but no luck.

**Comment by truepurpledino** [comment]
There is a way to separate fluid and item output into two hatches using only AE2 and subnetting. Here's a quick example taken from the discord:
![image](https://github.com/TheStaticVoid/StaTech-Industry/assets/75775263/d35552ad-b212-4f98-a711-15247ba0b0cc)

**Comment by AlexDiego123** [comment]
Thanks
