### ISSUE TITLE
Main menu panorama seed

### ISSUE THREAD

**Issue by mopsled** [TheStaticVoid/StaTech-Industry#501]
Hello! I'm curious if you still have the seed used to generate the [main panorama images](https://github.com/TheStaticVoid/StaTech-Industry/tree/main/config/fancymenu/panoramas/statechpanorama_01) displayed in the main menu. I'm not sure if all images are the same seed, but I'm referring specifically to these two:

[<img src="https://raw.githubusercontent.com/TheStaticVoid/StaTech-Industry/main/config/fancymenu/panoramas/statechpanorama_01/panorama/panorama_0.png">](https://github.com/TheStaticVoid/StaTech-Industry/blob/main/config/fancymenu/panoramas/statechpanorama_01/panorama/panorama_0.png)

[<img src="https://raw.githubusercontent.com/TheStaticVoid/StaTech-Industry/main/config/fancymenu/panoramas/statechpanorama_01/panorama/panorama_3.png">](https://github.com/TheStaticVoid/StaTech-Industry/blob/main/config/fancymenu/panoramas/statechpanorama_01/panorama/panorama_3.png)

It appears that these were added in #15.

I'm not even sure if these were generated in the current modpack, or if the seed would still even replicate after updates. But if you have that seed and it still might work, I'd be interested in making a base here. Thank you!

**Comment by TheStaticVoid** [comment]
seed:
x = -265
y = 1305

i think tectonic was installed

**Comment by TheStaticVoid** [comment]
correction, it was terralith

**Comment by mopsled** [comment]
> seed:
> x = -26
> z = 1305
> 
> i think tectonic was installed

Thank you for the response! Is the seed missing in this message?

**Comment by TheStaticVoid** [comment]
2677079749642946664

it didnt paste, weird

**Comment by mopsled** [comment]
@TheStaticVoid Wow, thank you! That was easy:

![Screenshot 2024-09-11 221629](https://github.com/user-attachments/assets/780aa93c-266f-452f-98b3-00cbe28ececf)

It looks a little different, but that's probably shaders. The mountain structure looks the same.

For anyone else interested, I installed `Terralith_1.19.3_v2.3.12.jar` (the latest `1.19.2`-supporting release) from [the Terralith download page](https://www.curseforge.com/minecraft/mc-mods/terralith/files/all?page=1&pageSize=20), and put this in the `mods/` folder inside the StaTech-Industry modpack folder. During world creation, click "More World Options…", use the seed above, and then go to the coordinates above.

Thanks a ton!

**Comment by TheStaticVoid** [comment]
only reason i still had this noted down was because someone asked in the discord and i was able to search back to it
