### ISSUE TITLE
Can't craft enderium hot ingot

### ISSUE THREAD

**Issue by kaibagley** [TheStaticVoid/StaTech-Industry#508]
Hey,

I can't force the EBF to craft the hot enderium ingots, it will only produce stainless steel hot ingots. I might be missing something obvious but thanks for any help

**Comment by TheStaticVoid** [comment]
You can lock the output hatch's inventory slot to only accept enderium hot ingots

**Comment by kaibagley** [comment]
How do I do that? I thought that might be the solution but I can't figure out how to do it.

The option in REI is greyed out

**Comment by TheStaticVoid** [comment]
you can drag the item from REI to the slot to lock it
