### ISSUE TITLE
Formation plane not placing blocks

### ISSUE THREAD

**Issue by kaibagley** [TheStaticVoid/StaTech-Industry#509]
Hey,

I can't seem to get the formation plane to actually place the block. When set to item it works fine, it's just the block setting.

I've seen some issues on the ae2 repo regarding this, and some posts on reddit etc. however they're from a while ago, and are closed. I'm using this exact setup: [youtube](www.youtube.com/watch?v=5z5S0ucWMGM)

Thanks!

**Comment by GW-Dev** [comment]
check your FTB Chunks fake player settings

**Comment by kaibagley** [comment]
Allowing all fake players worked like a charm. Thanks!!

I feel bad making GH issues for things like this that aren't bugs, is there somewhere better to ask things like this?

**Comment by GW-Dev** [comment]
Probably the pack discord: https://discord.gg/statech-industry-1080389179537637456
